### ISSUE TITLE
build.min.js uses `eval`

### ISSUE THREAD

**Issue by aquach** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#30]
If you check out https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/blob/c27bb63f6d98b8614aac3bd9db577d3d247e9e83/dist/build.js and search for `unsafeParse`, you'll see that because `goog.json.USE_NATIVE_JSON` is set to false, the closure compiler uses eval instead of `JSON.parse` to handle API respsonses. I don't know much about closure compiler, but I think that it should probably be configured to use native JSON.

Secondly, this issue silently broke all attribution and deeplinking data because of lines 1157-1159

```
        try {
          e(null, goog.json.parse(f.responseText), f.status);
        } catch (a) {
          e(null, {}, f.status);
        }
```

Because I have CSP enabled for my project, the `eval` failed and erroneously transformed from a "unsafe-eval blocked" error to a "Invalid JSON string" error, which in turn was caught and silently interpreted as the empty payload by the lines above. This was super confusing and probably should at least log an error.

**Comment by aaustin** [comment]
@aquach - Can you try the latest plugin? We've revamped this module entirely to a much more updated and stable version. This should be resolved.

**Comment by aquach** [comment]
The new Android app still uses eval via the `sendJavascript` method. See BranchSDK.java:808:

```
webView.sendJavascript(out);
```

which evaluates to a `eval` on the JS side of Cordova. Best practices are to use registered callbacks rather than arbitrarily evaluation of Javascript, which we block with our Content Security Policy.

**Comment by renesansz** [comment]
Hey @aquach ,
The reason why we used `sendJavascript` to execute a JS method is to compensate with iOS' implementation with `DeepLinkHandler` call.
At the moment, upon triggering the initSession in iOS `DeepLinkHandler` could not determine which callback is registered. So instead `evalJS` is used to execute the callback.
See line [134](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/src/ios/BranchSDK.m#L134)
But we are looking on alternative solution in order to fix this issue.
We'll let you know what we find.
