### ISSUE TITLE
Universal links and resume event issue

### ISSUE THREAD

**Issue by armenbadalyan** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#37]
Following the guide on integrating cordova plugin in Ionic app, I'm handling it like this:

```javascript
           if (window.branch) {
                window.branch.setDebug(true);
                document.addEventListener('resume', onResume, false);
                window.branch.init(BRANCH_KEY, {
                    isReferrable: true
                }, function (err, data) {
                    handleBranchResponse(data);
                });
                function onResume() {
                    window.branch.init(BRANCH_KEY, {
                        isReferrable: true
                    }, function (err, data) {
                        handleBranchResponse(data);
                    });
                }
            }
```

The cold start works just fine, I receive the deep link path as expected within the callback and navigate the user to the corresponding page of my app. However when I put the app in background mode and then resume it the callback of the second branch.init() in resume handler receives the same link parameter again although I haven't accessed the app by following the branch.io link. This results in user being taken to the same page again. This happens each time I pause and resume the app and the only way to fix it is to kill the app and start over.

**Comment by aaustin** [comment]
@armenbadalyan Sorry for the delay in responding. I saw in the support@ thread that you came up with a work around. This is a bit of a cop out, but we're in the process of revamping this module to be a thin wrapper around our native SDKs. https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/tree/project-restructure

I have personally confirmed that this issue is addressed in them. I will likely be merging to master this weekend or early next week. Sorry for not being helpful here.
